package Varsel::SchemaClass;

use strict;
use base qw/DBIx::Class::Schema::Loader/;

__PACKAGE__->loader_options(
    relationships   => 1,
    components      => qw/InflateColumn::DateTime/,
    # debug => 1,
);

=head1 NAME

Varsel::SchemaClass - DBIx::Class::Schema::Loader class

=head1 SYNOPSIS

See L<Varsel>

=head1 DESCRIPTION

Generated by L<Catalyst::Model::DBIC::Schema> for use in L<Varsel::Model::YRDB>

=head1 AUTHOR

Knut-Olav Hoven,,,

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the terms of GPL version 2.

=cut

1;

