CREATE TABLE forecast(
    id              INTEGER         NOT NULL    auto_increment,
    fc_to           DATETIME        NOT NULL,
    fc_from         DATETIME        NOT NULL,
    registered      TIMESTAMP       NOT NULL DEFAULT current_timestamp(),
    latitude        DOUBLE          NOT NULL,
    longitude       DOUBLE          NOT NULL,
    altitude        DOUBLE          NOT NULL,
    fog             VARCHAR(25),
    pressure        VARCHAR(25),
    clouds_low      VARCHAR(25),
    clouds_medium   VARCHAR(25),
    clouds_high     VARCHAR(25),
    cloudiness      VARCHAR(25),
    winddirection   VARCHAR(25),
    windspeed       VARCHAR(25),
    temp_unit       VARCHAR(25),
    temp_value      VARCHAR(25),
    symbol_no       VARCHAR(25),
    symbol_name     VARCHAR(25),
    precip_unit     VARCHAR(25),
    precip_value    VARCHAR(25),
    PRIMARY KEY (id)
) ENGINE InnoDB;
